name: Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
    inputs:
      Name:
        description: Workflow
        required: true
        default: 'Workflow'
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Workflow
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.DIRECTORY }}
          local-dir: ./site/
          state-name: .status.json
          exclude: |
            **/viewer/**
            **/assets/templates/projectsoft/images/**
            **/assets/templates/projectsoft/fonts/**
      - name: Remove Status
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteFiles: ".status.json;assets/cache/docid_*.php"
          workingDir: ${{ secrets.DIRECTORY }}
          ignoreSSL: 1
